- name: Install postgresql using homebrew
  community.general.homebrew:
    update_homebrew: yes
    name: postgres
    state: present
- name: Start postgresl
  command: /usr/local/bin/brew services start postgresql
- name: Check for default database
  command: "psql {{ ansible_user_id }} -c '\\q'"
  register: default_database
  ignore_errors: yes
- name: Create user's default database
  command: "createdb {{ ansible_user_id }}"
  when: default_database.failed == True