- name: change user shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
- name: create .zshrc
  file:
    path: ~/.zshrc
    state: touch
- name: Install starship prompt
  become: yes
  shell: 
    cmd: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
    creates: /usr/local/bin/starship
- name: Set EDITOR Environment variable
  blockinfile: 
    marker: "### {mark} SET VSCODE TO BE THE DEFAULT EDITOR"
    dest: ~/.zshrc
    block: |
      export EDITOR="code -w"
- name: Make sure /usr/local/bin exists and is writeable on macOS by admin users
  become: yes
  file:
    path: /usr/local/bin
    state: directory
    mode: 0775
    owner: root
    group: admin
  when: ansible_distribution|lower == 'macosx'
- name: Add starship to zshrc
  blockinfile:
    marker: "### {mark} Initialize Starship Prompt"
    mode: 0644
    path: ~/.zshrc
    create: yes
    block: eval "$(starship init zsh)"
